#!/bin/bash
set -e

if [ ! -d /home/me ]
then
  useradd -u $HOST_UID -o -m -s /bin/bash me
  groupmod -g $HOST_GID me
  groupadd -g $HOST_DOCKER_GID -o docker
  usermod -aG docker me
fi

chown -R me:me $JUPYTER_RUNTIME_DIR

exec gosu me python3 -m jupyter classic \
--ip=127.0.0.1 \
--ServerApp.token='' \
--ServerApp.base_url='' \
--port=8888 \
--port-retries=0 \
--FileCheckpoints.checkpoint_dir='/tmp/ipynb_checkpoints' \
--no-browser \
;
