#!/bin/sh
[ $# -ne 2 ] && echo invalid argument >&2 && exit 1
exec docker run --rm --init -i \
--net=container:jupyter_dood \
--volumes-from jupyter_dood \
-u $(id -u):$(id -g) -e HOME=/tmp --userns=host \
-w "${PWD}" \
-e TZ=Asia/Tokyo \
$(nvidia-smi >/dev/null 2>&1 && echo --gpus all -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all) \
--entrypoint='python3' \
"$1" -m ipykernel_launcher -f "$2"
